# Generated by Django 2.2 on 2019-05-21 08:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=20)),
                ('icon', models.FileField(blank=True, upload_to='')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.ManyToManyField(blank=True, to='weather.City')),
            ],
        ),
    ]
