# Generated by Django 2.1.3 on 2019-03-04 17:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20190212_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
